name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: NODE_ENV=production npm run build

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Stop PM2 Process
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "pm2 stop cristalux-admin || true"

      - name: Deploy with rsync
        run: |
          rsync -avz --delete build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/cristalux-admin/build/
          rsync -avz package.json ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/cristalux-admin/
          rsync -avz ecosystem.config.cjs ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/cristalux-admin/

      - name: Install dependencies on server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /var/www/cristalux-admin && npm install --production"

      - name: Start PM2 Process
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /var/www/cristalux-admin && pm2 start cristalux-admin --update-env"
